# Generated by Django 2.1 on 2019-07-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_movie_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Awards',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Poster',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
