# Generated by Django 2.1 on 2019-07-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='total_comments',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
