# Generated by Django 2.1 on 2019-07-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_movie_total_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='total_comments',
        ),
    ]
