# Generated by Django 2.1 on 2019-07-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_movie_total_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='totalSeasons',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
