# Generated by Django 2.1 on 2019-07-09 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rating_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='created',
        ),
        migrations.AddField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
